export default {
    path:'/region',
    name:'region',
    component:()=>
    import('@/components/pages/hub/index.vue'),
    children:[
        {
            path:'chinese',
            name:'chinese',
            component:()=>
            import('@/components/pages/china/china.vue'),
        },
        {
            path:'rumor',
            name:'rumor',
            component:()=>
            import('@/components/pages/rumor/rumor.vue')
        }
    ]
}