export default {
    path:'/region',
    name:'region',
     component:()=>
     import('@/pages/index/index.vue'),
    children:[
        {
            path:'chinese',
            name:'chinese',
            component:()=>
            import('@/pages/china/china.vue'),
        },
        {
            path:'rumor',
            name:'rumor',
            component:()=>
            import('@/pages/rumor/rumor.vue')
        },
        {
            path:'broadcast',
            name:'broadcast',
            component:()=>
            import('@/pages/broadcast/broadcast.vue')
        },
        {
            path:'knowledge',
            name:'knowledge',
            component:()=>
            import('@/pages/knowledge/knowledge.vue')
        }
    ]
}